steps:
- name: 'squidfunk/mkdocs-material:5.5.6'
  entrypoint: sh
  args: ['-c', 'mkdocs build -v']
- name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args: ['-cxe', 'cd site && gsutil -m cp -r -z "css,htm,html,js,json,mjs,svg,xhtml" "." "gs://docs.heroiclabs.com/docs"']
  timeout: 3600s
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'setmeta', '-r', '-h', 'Cache-Control:must-revalidate, max-age=3600', 'gs://docs.heroiclabs.com/*']
timeout: 7200s
