= Unity

The Nakama Unity client gives you access to all of Nakama's capabilities from within the Unity framework.

NOTE: If you haven't installed and started a Nakama server yet, follow the link:../install[install guide] before continuing.

If you're looking for clients for other frameworks, take a look at our link:./unreal.adoc[Unreal Engine client] (which is in development). We're also working on a Defold client and will share more news soon. For more information, or to get involved, join our https://gitter.im/heroiclabs/nakama[community^]!

== Requirements

To develop using the Unity client you will need:

* a https://unity3d.com/get-unity/download[Unity^] 5.4 development environment
* a link:../install[Nakama^] server installed and running.

== Installation

There are two ways to install the Unity client:

 * link:https://github.com/heroiclabs/nakama-unity/releases[get the latest version from our GitHub releases page]
 * or https://www.assetstore.unity3d.com/en/#!/content/81338[install from the Unity Asset Store].

Choosing between the two methods will depend on what's important to you:

* *GitHub:* you'll get the latest client with access to all current Nakama features
* *Unity Asset Store:* you'll get dependency management but an older version of the client.

If you download from GitHub, the file is named `Nakama.unitypackage` and contains a copy of all source code as well as the DLL dependencies required by the client.

To include the Unity client in your project, either drag or import the `.unitypackage` into your Unity editor project.

== Connecting to a server

Connecting to the server from your Unity C# code is a three step process:

1. Create an `INClient` object
2. If necessary, modify the connection details.
3. Obtain a session with the server.

=== Creating the connection

Your connection to the server is through an `INClient` object. To make the connection to a local Nakama instance, you'll need to create a new C# script in the Unity editor and then modify the default code:

[source,csharp]
----
using UnityEngine;
using System.Collections;
using Nakama;

public class NewBehaviourScript : MonoBehaviour {
  void Start() {
    INClient client = NClient.Default("defaultkey");
  }

  void Update() {
  }
}
----

TIP: *Run with a local server*
This guide assumes you're running a Nakama server locally using the default connection details of `127.0.0.1` and port `7350`. You can read more in our guide to link:../../start-server.adoc[starting the server].

If you're not familiar with sharing objects across game objects, you can read more about https://docs.unity3d.com/Manual/ControllingGameObjectsComponents.html[controlling the sharing of objects^] in the Unity documentation.

=== Changing the default connection settings

In production, Nakama will be running as a cluster on separate machines from the game application servers where your Unity code is running.

You can change the default connection settings using an `NClient.Builder`:

[source,csharp]
----
INClient client = new NClient.Builder("defaultkey")
    .Host("myprivate.server.com")
    .Port(8080)
    .SSL(true)
    .Build();
----

WARNING: *In production*
You must *not* use the default server key `"defaultkey"` in a production environment. You must change it in the link:../configure/index.adoc[configuration] settings.

=== Connecting the client to the server

Once you are authenticated, you can connect the `client` instance to the server.

[source,csharp]
----
// First obtain a session:
// client.Register(...) or client.Login(...)
// We recommend caching the resulting `session` locally.
// Then connect:
client.Connect(session);
----

== Logs and errors

Both the Nakama server and client generate logs that can help you to identify issues in development.

To log all messages between the client and server, enable `Trace` when you create an `INClient`:

[source,csharp]
----
#if UNITY_EDITOR
var client = new NClient.Builder("defaultkey").Trace(true).Build();
#else
var client = NClient.Default("defaultkey");
#endif
----

`#if` preprocessor directives are used so `Trace` is only enabled in Unity editor development. For more complex directives with "debug" vs "release" builds have a look at the Unity guide to https://docs.unity3d.com/Manual/PlatformDependentCompilation.html[platform dependent compilation^].

All errors in the Unity client implement `INError`, which contains details on the source of an error:

[source,csharp]
----
Debug.LogErrorFormat("Error occurred: {0}", error.Message);
----

TIP: *Open-source*
The Unity client is https://github.com/heroiclabs/nakama-unity[open-source^] under the Apache 2.0 License on GitHub.
Please report issues and contribute code to help us make it better.

== Next Steps

XXX: Update links to /development rather than client

Now that you have a client instance, you can start taking advantage of the Nakama features such as

* link:../clients/user.adoc[Creating and fetching users]
* link:../clients/groups.adoc[Add groups] or link:../client/friends.adoc[friends]
* link:../clients/realtime-chat.adoc[Realtime Chat]
* link:../clients/realtime-multiplayer.adoc[Create multiplayer matches]
