= Docker

It's recommended to run Nakama and the database (cockroachdb) as separate containers and connect them together via Docker's virtual network on the host machine. This guide will show you how to install and configure all resources together so it can be run in a single step.

TIP: *Install Docker*
https://docs.docker.com/engine/installation/[Install Docker and Docker-Compose^]. This is needed for following this guide.

== Run Nakama with Docker

1. Save the content of the file https://raw.githubusercontent.com/heroiclabs/nakama/master/install/docker/docker-compose.yml[`docker-compose.yml`^] file onto your computer.
+
[source,bash]
----
wget https://raw.githubusercontent.com/heroiclabs/nakama/master/install/docker/docker-compose.yml
----
+
This will download `docker-compose.yml` to your current working directory.
+
2. Run the following command:
+
[source,bash]
----
docker-compose up
----
+
This will download the latest cockroachdb and Nakama images published on Docker Hub.
+
3. You have both CockroachDB and Nakama running on your machine.
4. Navigate to http://127.0.0.1:7351[http://127.0.0.1:7351^] to check that you can view Nakama's embedded dashboard.

All server logs are printed to the console as part of the `docker-compose` output.

== Updating Docker to the latest image

Application containers should not store application data. This way you can replace containers with its newer version at any time by executing the following commands:

[source,bash]
----
docker-compose down # this will remove stop and remove all containers
docker pull nakama
docker-compose up
----

== Configuring the client

By default the server is started on `127.0.0.1:7350` and dashboard is reachable at http://127.0.0.1:7351[http://127.0.0.1:7351^].

CockroachDB is started on `127.0.0.1:26257` and it's dashboard is available at http://127.0.0.1:8080[http://127.0.0.1:8080^].

Follow one of the client guides to connect to the server:

- https://heroiclabs.com/docs/clients/unity/[Unity^]

== Stop the containers

You can stop `docker-compose` while it is running with `ctrl-c`. You can also run `docker-compose stop` in the same directory as `docker-compose.yml` and all containers will be shutdown gracefully. Your data within these containers is still safe. You can re-run the containers by running `docker-compose up`.

To stop and purge all stored data, containers, and images from your machine. Run `docker-compose down`.
