= Install

Installing Nakama is very simple as Nakama ships as a single binary.

Currently the Nakama server only supports x86_64 architectures. If you'd like to build from source, please refer to the https://github.com/heroiclabs/nakama/blob/master/README.md#build-from-source[GitHub ReadMe^].

NOTE: **Nakama requires CockroachDB**
To use Nakama, you'd also need to install https://www.cockroachlabs.com/docs/install-cockroachdb.html[CockroachDB^].

== macOS

=== Homebrew

. Install http://brew.sh/[Homebrew^].
. Run our brew recipe to get the Nakama code and build the binary:
+
[source,bash]
----
brew install https://raw.githubusercontent.com/heroiclabs/nakama/master/install/local/nakama.rb
----

=== Binary

Native binaries are provided for OS X 10.8 (Mountain Lion) and above.

1. Download the latest https://github.com/heroiclab/nakama/releases[Nakama tarball for macOS^].
2. Extract the binary:
+
[source,bash]
----
tar xfz nakama.macos.tgz
----
+
3. Add the directory containing the binary to your `PATH`. This makes it easy to execute link:../configure.adoc#command-line-options[Nakama commands^] from any shell.

== Windows

*TODO*

=== Chocolatey

*TODO*

=== Binary

*TODO*

== Linux

We currently only support Binary releases for the most popular Linux distributions.

=== Binary

1. Download the latest https://github.com/heroiclab/nakama/releases[Nakama tarball for Linux^].
2. Extract the binary:
+
[source,bash]
----
tar xfz nakama.linux.tgz
----
+
3. Add the directory containing the binary to your `PATH`. This makes it easy to execute link:../configure.adoc#command-line-options[Nakama commands^] from any shell.

=== systemd

You can optionally use the following systemd script to setup Nakama to start as a service.

Full support for systemd is planned. For now, you’ll have to create a the configuration files manually.

1. Create the service file, `/usr/lib/systemd/system/nakama.service`:
+
Please note that you'll need to update the paths within the systemd configuration.
+
[source,bash]
----
[Unit]
Description=Nakama server

[Service]
ExecStart=/path/to/nakama --config /path/to/nakama/config.yml
KillMode=process

[Install]
WantedBy=multi-user.target
----
The `chmod` for this file should be 644 (`sudo chmod 644 /usr/lib/systemd/system/nakama.service`).

2. Enable and run the service:
+
[source,bash]
----
sudo systemctl enable nakama
sudo systemctl start nakama
----

== Next stage

link:../start-server.adoc[Quick start^] a single- or multi-node cluster locally and talk to it via your client.
