= User > Google Social Login | Nakama Client

== Google account authentication

Google's account authentication is ideal for games running on Android and can just as easily be used for games on other platforms, thanks to the ubiquity of Google accounts.

=== Requirements

To authenticate player accounts using Google, you'll first need to get an OAuth `AccessToken` from Google. 

You can either link:https://developers.google.com/identity/protocols/OAuth2[generate this yourself^] or use Google's link:https://github.com/playgameservices/play-games-plugin-for-unity[Play Games plugin for Unity^].

=== Register and log-in users

Once you have obtained the `AccessToken` for the user, you can use it to register and then authenticate the user with Nakama.

XXX: As with Facebook, I think we could split this out into separate registration and auth examples, and add some more context to explain what is going on.

[docs__code-switch]
* image:/images/svg/unity.svg[Unity] link:#[Unity, role="code-unity"]

[source,csharp, role="docs__code-display code-unity"]
----
String oauthToken = "access-token-from-google";
var message = NAuthenticateMessage.Google(oauthToken);
client.Login(message, (INSession session) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.Log ("Could not login. Attempting to register.");
  client.Register(message, (INSession session) =>
  {
    client.Connect(session);
    Debug.Log ("Successfully registered and logged in.");
  }, (INError error) =>
  {
    Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
  });
});
----

In the examples above you have registered and/or logged in a user, and connected the application to your Nakama server instance.

== Next Steps

You now have a user logged in with Google, you can now:

* link:../clients/groups.adoc[Add groups] or link:../client/friends.adoc[friends]
* link:../clients/realtime-chat.adoc[Realtime Chat]
* link:../clients/realtime-multiplayer.adoc[Create multiplayer matches]
