= Groups

Groups connect a set of users and give them a shared space to interact through online presence tracking, persistent chat, and more. Users can join groups with their friends, new people they meet, or by looking for groups in their area.

Membership to a group grants privileges like access to a private group link:./realtime-chat.adoc[chat topic], link:./realtime-chat.adoc[chat history], and more.

== Types

To join *private* groups, users send a request for membership. Group admins can review pending requests and accept or reject each user.

*Public* groups can be joined by any user at any time, without needing approval.

== Membership

Groups have *members* and *admins*. Both participate in group activities equally, but admins have additional privileges and responsibilities.

All users joining a group do so as regular members, and may be promoted later by existing admins.

== Admins

Admins are group members with additional privileges, and are responsible for:
* Changing group config, description, and more.
* Approving or rejecting requests from other users to join the group.
* Removing members and admins.
* Appointing additional admins.

The user that creates a group is automatically assigned as the first admin, and may then promote others to admin status.

All admins have equal privileges, and may remove other admins from the group.

TIP *Leaving a group while admin*
Admins are allowed to leave groups just like regular members, with one exception: the last admin in a group cannot leave. They should promote at least one new admin from the other members, or remove and disband the group entirely.

== Basics

All users in Nakama are allowed to create and manage groups, allowing users to connect and interact freely.

=== Create

To create a group users must choose a name, and may submit other optional fields: a description, an avatar URL, a lang tag (such as "en_US"), and additional application-specific metadata. Nakama will use this data to create the group, and ensure it appears in the correct listings based on its properties.

The user creating the group will automatically be added as a member with admin privileges.

=== Update

After a group is created, its admins may update it at any time. All group properties available at creation time can be edited later: name, description, avatar URL, lang tag, and additional metadata.

=== Remove

Group admins are allowed to disband the group itself, and remove all its members. Users cannot undo this operation.

== Finding groups

Group listings allow users to find new groups to join based on activity, location, and more.

Nakama provides 3 main ways to find groups:
* By creation time, allowing users to find established groups first.
* By member count and updated at, to find recently active groups up to a given size.
* By lang tag and member count, to find groups in the user's area/country/timezone or primarily speaking the same language.

With these core building blocks users can quickly find one or more relevant groups to join and interact with based on interests, how frequently members are available, preferred language, and more.

// list groups sample code

TIP *Group listing pagination*
A cursor is returned with group listing results, use this in further calls to paginate results.

=== Current groups

Users can list groups they are already a part of. This provides fast access to all memberships for each user, for further operations or individual group access.

=== Join

Any user can choose to join a group, which will be processed by Nakama one of two ways:
* With *public* groups, the user is immediately added as a group member without further confirmation.
* For *private* groups, a join request is created and submitted to group admins for review. The user is not added as a member unless that request is accepted by any of the group's current admins.

=== Leave

Users can leave groups at their discretion. When the leave operation is accepted, the user immediately loses access to all group privileges such as the link:./realtime-chat.adoc[chat topic], link:./realtime-chat.adoc[chat history].

TIP *Leaving a group while admin*
The last admin cannot leave a group, they must promote at least one other admin.

== Moderation

Admins are responsible for managing the group and its ongoing maintenance, including the member roster, and are empowered with the privileges to achieve this.

=== Accepting join requests

When users attempt to join private groups, a join request will be created. Admins can obtain a list of these requests, and accept or reject each one. When a request is accepted that user becomes a member.

=== Promote

Any admin may promote a regular group member to admin status. This ensures there is likely to be an admin presence available at most times to handle group moderation and leadership.

=== Kick

Admins can kick members or other admins from groups, for any reason. This permanently removes that user from the group, but does not prevent them from joining at a later point if needed.
