= Groups

Groups connect a number of users and give them a space to interact through online presence tracking, persistent chat, and more. Users can join groups with their friends, new people they meet, or by looking for groups in their area.

Membership to a group allows privileges like access to a private group link:./realtime-chat.adoc[chat topic], link:./realtime-chat.adoc[chat history], and more.

== Types

To join *private* groups, users send a request for membership. Group admins can review pending requests and accept or reject each user.

*Public* groups can be joined by any user at any time, without needing approval.

== Basics

All users in Nakama are allowed to create and manage groups, allowing users to connect and interact freely.

=== Create

To create a group users must choose a name, and may submit other optional fields: a description, an avatar URL, a lang tag (such as "en_US"), and additional application-specific metadata. Nakama will use this data to create the group, and ensure it appears in the correct listings based on its properties.

The user creating the group will automatically be added as a member with admin privileges.

[source,csharp]
----
*TODO*
----

=== Update

After a group is created, its admins may update it at any time. All group properties available at creation time can be edited later: name, description, avatar URL, lang tag, and additional metadata.

[source,csharp]
----
*TODO*
----

=== Remove

Group admins are allowed to disband the group itself, and remove all its members. Users cannot undo this operation.

[source,csharp]
----
*TODO*
----

== List

Group listings allow users to find new groups to join based on activity, location, and more.

Nakama provides 3 main ways to find groups:
* By creation time, allowing users to find established groups first.
* By member count and updated at, to find recently active groups up to a given size.
* By lang tag and member count, to find groups in the user's area/country/timezone or primarily speaking the same language.

With these core building blocks users can quickly find one or more relevant groups to join and interact with based on interests, how frequently members are available, preferred language, and more.

[source,csharp]
----
*TODO*
----

TIP *Group listing pagination*
A cursor is returned with group listing results, use this in further calls to paginate results.

== Membership

*TODO*
- how it works
- listing groups user is part of

=== Join

*TODO*
- expand on public vs private

=== Leave

*TODO*

== Admin

*TODO*
- admin privileges
- can't leave if last admin
- admins have equal privileges

=== Promote

*TODO*

=== Kick

*TODO*
