= Groups | Nakama server documentation

Groups connect a set of users and give them a shared space to interact through online presence tracking, persistent chat, and more. Users can join groups with their friends, new people they meet, or by looking for groups in their area.

Membership to a group grants privileges like access to a private group link:../realtime-chat.adoc[chat topic], link:../realtime-chat.adoc[chat history], and more.

Groups have *members* and *admins*. Both participate in group activities equally but admins have additional privileges and responsibilities. All users joining a group do so as regular members and may be promoted later by existing admins.

== Join

Any user can choose to join a group, which will be processed by Nakama one of two ways:

* With *public* groups, the user is immediately added as a group member without further confirmation.
* For *private* groups, a join request is created and submitted to group admins for review. The user is not added as a member unless that request is accepted by any of the group's current admins.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See below.

var message = NGroupJoinMessage.Default(groupId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully joined the group"); // -- If group is private, an join-request invitation is sent
}, (INError error) => {
  Debug.LogErrorFormat ("Could not join group: '{0}'.", error.Message);
});
----

Users can list groups they've already joined. This provides fast access to all memberships for each user for further operations or individual group access.

== Finding groups

Group listings allow users to find new groups to join based on activity, location, and more.

Nakama provides 3 main ways to find groups:

* By creation time - allowing users to find established groups first.
* By member count and updated at - to find recently active groups up to a given size.
* By lang tag and member count - to find groups in the user's area/country/timezone or primarily speaking the same language.

With these core building blocks users can quickly find one or more relevant groups to join and interact with based on interests, how frequently members are available, preferred language, and more.

[source,csharp]
----
var message = new NGroupsListMessage.Builder()
  .OrderByAsc(true)
  .FilterByLang("en")
  .Build();

client.Send(message, (INResultSet<INGroup> results) =>
{
  foreach (INGroup nakamaGroup in results.Results) {
    Debug.LogFormat ("Group ID: '{0}'", nakamaGroup.Id);
  }
}, (INError error) => {
  Debug.LogErrorFormat ("Could not list groups: '{0}'.", error.Message);
});
----

TIP: *Group listing pagination*
A cursor is returned with group listing results; use this in further calls to paginate results.

== List joined groups

The Client can list the groups the user is part of. This list includes the groups the user is a member, an admin or has sent a request to join (for private groups).

[source,csharp]
----
var message = NGroupsSelfListMessage.Default();
client.Send(message, (INResultSet<INGroup> results) =>
{
  foreach (INGroup nakamaGroup in results.Results) {
    Debug.LogFormat ("Group ID: '{0}'", nakamaGroup.Id);
  }
}, (INError error) => {
  Debug.LogErrorFormat ("Could not list groups: '{0}'.", error.Message);
});
----

== List users in a group

The Client can list the users in a given group.

[source,csharp]
----
byte[] groupId = null; // Some groupId
var message = NGroupUsersListMessage.Default(groupId);
client.Send(message, (INResultSet<INGroupUser> results) =>
{
  foreach (INGroupUser groupUser in results.Results) {
    Debug.LogFormat ("User ID: '{0}'", groupUser.Id);
  }
}, (INError error) => {
  Debug.LogErrorFormat ("Could not list users in group: '{0}'.", error.Message);
});
----

== Leave

Users can leave groups at their discretion. When the leave operation is accepted, the user immediately loses access to all group privileges such as the link:../realtime-chat.adoc[chat topic], link:../realtime-chat.adoc[chat history].

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.

var message = NGroupLeaveMessage.Default(groupId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully left the group");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not leave group: '{0}'.", error.Message);
});
----

== Create

To create a group users must choose a name and may submit other optional fields:

* Group Description
* Avatar URL
* Lang Tag (such as `en-US`)
* Additional application-specific metadata.

Nakama will use this data to create the group and ensure it appears in the correct listings based on its properties.

The user creating the group will automatically be added as a member with admin privileges.

[source,csharp]
----
var message = new NGroupCreateMessage
  .Builder("Group Name")
  .Description("Group Description")
  .Lang("en-US")
  .Private(true)
  .Build();

client.Send(message, (INGroup group) =>
{
  Debug.Log ("Successfully created a private group");
  Debug.LogFormat ("Group ID: {0}, Group Name: {1}", group.Id, group.Name);
}, (INError error) => {
  Debug.LogErrorFormat ("Could not create group: '{0}'.", error.Message);
});
----

== Update

After a group is created, its admins may update it at any time. All group properties available at creation time can be edited later.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.

var message = new NGroupUpdateMessage
  .Builder(groupId)
  .Name("Updated Name")
  .Description("Updated Group Description")
  .Build();

client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully update group");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not update group: '{0}'.", error.Message);
});
----

== Remove

Group admins are allowed to disband the group itself and remove all its members.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.

var message = NGroupRemoveMessage.Default(groupId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully removed group");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not remove group: '{0}'.", error.Message);
});
----

== Admins

Admins are group members with additional privileges, and are responsible for:

* Changing group config, description, and more.
* Approving or rejecting requests from other users to join the group.
* Removing members and admins.
* Appointing additional admins.

The user that creates a group is automatically assigned as the first admin, and may then promote others to admin status. All admins have equal privileges, and may remove other admins from the group.

TIP: *Leaving a group*
Admins are allowed to leave groups just like regular members, with one exception: the last admin in a group cannot leave. They should promote at least one new admin from the other members, or remove and disband the group entirely.

=== Accepting join requests

When users attempt to join private groups a join request will be created. Admins can obtain a list of these requests and accept or reject each one. When a request is accepted that user becomes a member.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.
byte[] userId = null; // -- UserID of the member you'll like to accept or add to the group.

var message = NGroupAddUserMessage.Default(groupId, userId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully added user to group");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not add user to group: '{0}'.", error.Message);
});
----

=== Promote

Any admin may promote a regular group member to admin status. This ensures there is likely to be an admin presence available at most times to handle group moderation and leadership.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.
byte[] userId = null; // -- UserID of the member you'll like to accept or add to the group.

var message = NGroupPromoteUserMessage.Default(groupId, userId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully promoted user to admin");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not promote user to admin: '{0}'.", error.Message);
});
----

=== Kick

Admins can kick members or other admins from groups for any reason. This permanently removes that user from the group but does not prevent them from joining at a later point if needed.

[source,csharp]
----
byte[] groupId = null; // -- Get this by fetching a list of groups. See above.
byte[] userId = null; // -- UserID of the member you'll like to accept or add to the group.

var message = NGroupKickUserMessage.Default(groupId, userId);
client.Send(message, (bool completed) =>
{
  Debug.Log ("Successfully kicked user from group");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not kick user from group: '{0}'.", error.Message);
});
----
