= Script Runtime | Nakama server documentation

The script runtime integrates the Lua language with the Nakama server. It is useful to run custom logic which isn't running on the device or browser. The code you deploy with the server can be used immediately by all clients so you can change behavior on the fly and add new features faster.

Some suggestions on when to use the runtime:

* Enforce rules for how many friends a user can have or whether they should be able to join a group.
* Add a reward for a video Ad a user has watched.
* Update the coins or inventory in a user's virtual wallet.
* Run authoritative logic or perform validation checks.
* Integrate with a custom server or HTTP services.

== Example

An example of a function registered for RPC by clients:

[source, lua]
----
local nk = require("nakama")
local nx = require("nakamax")

local function some_rpc_func(context, payload)
  nk.logger_info(("%q"):format(payload))
  -- "payload" is a byte array so we'll JSON decode it
  local json = nx.json_decode(payload)
  local id = nx.uuid_v4()
  -- create a leaderboard with the json as metadata
  nk.create_leaderboard(id, "desc", "0 0 * * 1", json, false)
  return nx.json_encode({["id"] = id})
  -- will return "{'id': 'a generated UUID'}" (JSON) as bytes
end

nk.register_rpc(some_rpc_func, "some_rpc_func_id")
----

The Lua module above registers a function to handle messages received over RPC from clients. There are a number of register functions in the "nakama" module.

The "nakamax" module is an experimental namespace for functions which are utilities or are subject to change before standardization. You can track changes to the runtime in the release notes for each major/minor server release. You can see a list of the available functions in each module link:./function-reference.adoc[here].

== Register functions

At startup the server will scan all files within the "data/modules" folder or the folder specified in the YAML configuration. All files with the ".lua" extension will be loaded and evaluated as part of the bootup sequence. All code in each module will be run and can be used to register functions which can operate on messages from clients as well as execute logic on demand.

There are four ways to register a function within the runtime each of which is used to handle specific behavior between client and server.

=== `register_before`

Any function may be registered to intercept a message type received from a client and operate on it (or reject it) based on custom logic. This is most useful to enforce specific rules on top of the standard features in the server.

[source, lua]
----
local function limit_friends(context, payload)
  local user = nk.user_fetch_id({context.user_id})
  -- Assume we've stored a user's level in their metadata
  local json = nx.json_decode(user.metadata)
  if json.level <= 10 then
    error("Must reach level 10 before you can add friends.")
  end
  return payload
end
nk.register_before(limit_friends, "TFriendAdd")
----

The code above fetches the current user's profile and checks the metadata (which is structured as "{level: 12}"). If a user's level is too low an error is thrown to prevent the `TFriendAdd` message from completing in the server pipeline.

TIP: **Pipeline passthrough**
You must remember to pass through the payload (which contains the message) to continue in the server. See the "return payload" code above.

=== `register_after`

Similar to the "register_before" function you can attach a function to operate on a message type but instead execution happens after the standard feature of the server has executed. The function handler will execute asynchronously after the response message has been sent to a client. This is useful to run custom logic after some server message type has been processed.

[source, lua]
----
local function send_reward(context, payload)
  local value = {
    user_ids = {payload.user_id}
  }
  local json = nx.json_encode(value)
  local new_records = {
    {bucket = "mygame", collection = "rewards", record = "reward", user_id = context.user_id, value = json}
  }
  nk.storage_write(new_records)
end
nk.register_after(send_reward, "TFriendAdd")
----

The code above writes a reward to a user's storage when they add a friend.

=== `register_http`

Sometimes it's useful to create HTTP REST handlers which can be used by web services and ease integration into custom server environments. You should not use "register_http" with clients - instead use "register_rpc".

[source, lua]
----
local function http_func(context, payload)
  local message = nx.json_encode(payload)
  nk.logger_info(message)
  return {["context"] = context}
end
nk.register_http(http_func, "http_func_path")
----

This function can be called with any standard HTTP library. In cURL you could execute the function with the server default port and host:

[source, bash]
----
curl -X POST "http://127.0.0.1:7350/runtime/http_func_path?key=defaultkey" \
     -d "{'some': 'data'}" \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json'
----

WARNING: **Http key**
You should change the default HTTP key before you deploy your code in production.

=== `register_rpc`

Some logic between client and server is best handled as RPC functions which clients can execute.

[source, lua]
----
local function custom_rpc_func(context, payload)
  -- "payload" is a byte array sent by the client we'll JSON decode it
  local json = nkx.json_decode(payload)
  nk.logger_warn(("%q"):format(json))
  return nkx.json_encode(json)
end
nk.register_rpc(custom_rpc_func, "custom_rpc_func_id")
----

The code above registers a function with the identifier "custom_rpc_func_id". This ID can be used within client code to send an RPC message to execute the function and return the result. Results are always returned as a Lua string (or optionally "nil").

TIP: **Function Reference**
Have a look at the link:./function-reference.adoc[function reference] for a full list of available functions in the builtin modules.

All functions registered against the server runtime will receive a "context" table as the first argument (and "payload" as the second) which contains fields which are relevant to the execution:

[cols="1,3", options="header"]
|===
| Field | Purpose

| `context.user_id`
| The user ID associated with the execution context. It will always be `nil` on `register_http`.

| `context.user_handle`
| The user handle associated with the execution context. It will always be `nil` on `register_http`.

| `context.user_session_exp`
| The user session expiry in milliseconds associated with the execution context. It will always be `nil` on `register_http`.

| `context.execution_mode`
| The mode associated with the execution context. The value is a string which represents one of these enumerated values: "after", "before", "http", or "rpc".

| `context.env`
| A table of key/value pairs which are defined in the YAML configuration of the server. This is useful to store API keys and other secrets which may be different between Nakama servers in production and in development.
|===

== Handle errors

You can handle errors like you would normally in Lua code. If you want to trap the error which occurs in the execution of a function you'll need to execute it via `pcall` as a "protected call".

[source, lua]
----
local function will_error()
  error("This function will always throw an error!")
end

if pcall(will_error) then
  -- no errors with "will_error"
else
  -- handle errors
end
----

The function `will_error` uses the `error` function in Lua to throw an error with a reason message. The `pcall` will invoke the `will_error` function and trap any errors. We can then handle the success or error cases as needed.

We recommend you use this pattern with some of the builtin modules in Nakama server:

[source, lua]
----
local nk = require("nakama")
local status, res = pcall(nk.user_fetch_handle, {"22e9ed62"})
if status then
  -- do work with "res"
else
  -- handle error in "res" variable
  print(res)
end
----

== Logs

If you want to write a message to the server logs you can use the `logger_*` functions in the "nakama" module. There are no limits on how many log messages can be written or the size of each log line.

[source, lua]
----
local message = ("%q"):format(47)
nk.logger_info(message)
----

== Restrictions

The Lua VM embedded in the server uses a restricted set of Lua standard library modules. This ensures the script sandbox cannot tamper with OS input/output or the filesystem.

The list of available modules are: base module, "math", "os", "string", and "table".
