= User

The core component of every client interaction with Nakama is the user. A user represents a unique identity in Nakama, and can have one or more unique identifiers attached - device IDs, email addresses, Facebook accounts, and more.

== Authenticate

Authenticating with Nakama requires the server key. This key can be found in the link:../../configure.adoc[server configuration]. We strongly suggest that you **use a unique key on your production servers**.

In the Unity client, an `INClient` can be constructed with the server key like below:

[source,csharp]
----
private static readonly string ServerKey = "YourServerKey";
private readonly INClient client;

public MyClass() {
  client = new NClient.Builder(ServerKey).Build();
}
----

Once you are authenticated, you'll need to connect the `client` instance to the server.

[source,csharp]
----
// First obtain a session:
// client.Register(...) or client.Login(...)
// We recommend caching the resulting `session` locally.
// Then connect:
client.Connect(session);
----

There are three main login mechanisms so far; ID-based Login, Social Login, and Email Login. Currently supported Social Login providers include Facebook, Google, Steam and GameCenter. You have the option of providing any combination of login options.

=== Device ID

The most effortless way of authenticating a user with Nakama is to use a Device ID. This can be done entirely without user interaction, so the user experience is completely frictionless.

TIP: **Device ID login as guest users.**
They don't require any information from the user to create although you'll want to use an identifier from the client device which can be used to recover the user if necessary.

Anonymous logins are performed by sending Nakama a single field representing a unique identifier, usually a UDID or a Device ID.
This unique identifier can be used again later to retrieve the same user for example when recovering the user after the game is removed and reinstalled.

TIP: **Cache Device ID**
The UDID from mobile devices like Android and iOS are changed often by the operating system vendors.
They are not reliable sources for uniquely identifying the device; you should cache the UDID once obtained so the game can use it to recover the account.

In the Unity Client, device ID authentication is done as below once you have an instance of `INClient`:

[source,csharp]
----
// Let's check storage if there was an ID already generated
// if not, let's generate a new one and persist it.
// Alternatively, on mobile devices you may use a native system device ID.
string id = PlayerPrefs.GetString("ID");
if (string.IsNullOrEmpty (id)) {
  id = SystemInfo.deviceUniqueIdentifier;
  PlayerPrefs.SetString ("ID", id);
}

var message = NAuthenticateMessage.Device(id);
client.Register(message, (INSession newSession) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
});
----

If the user has already registered with the device ID you should use:

[source,csharp]
----
var request = NAuthenticateMessage.Device(id);
client.Login(request, (INSession session) => {
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) => {
  Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
});
----

=== Email

Email based login is for users that still want to log in, but would prefer not to connect through their social or platform accounts. Users are registered and logged in via an email address and password.

==== Registration

[source,csharp]
----
string email = "email@example.com"
string password = "password"
var message = NAuthenticateMessage.Email(email, password);
client.Register(message, (INSession newSession) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not register user: '{0}'.", error.Message);
});
----

==== Login

[source,csharp]
----
string email = "email@example.com"
string password = "password"
var message = NAuthenticateMessage.Email(email, password);
client.Login(message, (INSession newSession) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
});
----

=== Social Login

Nakama provides a simple mechanism for your game to implement social login, allowing your gamers to sign in using Facebook, Google, Steam or GameCenter and start playing right away.

To perform a social login, ensure the gamer is first logged into their social account. Once the social authentication is complete, the last step is to send Nakama the access token available. This is usually an OAuth 2.0 access token, but varies by social provider.

==== Facebook

You will need the Facebook Unity SDK which can be downloaded https://developers.facebook.com/docs/unity/downloads[here^]. Follow the https://developers.facebook.com/docs/unity/examples[Facebook Unity Examples^] on how to add the asset to your project. You must also complete the instructions on https://developers.facebook.com/docs/unity/reference/current/ConfigureiOSAndroid[Facebook's developer guide^] on how to configure your iOS or Android client.

You'd need to ensure that the Facebook profile has been registered with Nakama before attempting to login with it.

[source,csharp]
----
// you must call FB.Init as early as possible at game startup
if (!FB.IsInitialized) {
  FB.Init (() => {
    if (FB.IsInitialized) {
      FB.ActivateApp();
      // Use a Facebook access token to create a user account
      var oauthToken = Facebook.Unity.AccessToken.CurrentAccessToken.TokenString;
      var message = NAuthenticateMessage.Facebook(oauthToken);
      client.Login(message, (INSession session) =>
      {
        client.Connect(session);
        Debug.Log ("Successfully logged in.");
      }, (INError error) =>
      {
        Debug.Log ("Could not login. Attempting to register.");
        client.Register(message, (INSession session) =>
        {
          client.Connect(session);
          Debug.Log ("Successfully registered and logged in.");
        }, (INError error) =>
        {
          Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
        });
      });
    }
  });
}

// Execute in a button or UI component within your game
FB.Login("email", (ILoginResult result) => {
  if (FB.IsLoggedIn) {
    var accessToken = Facebook.Unity.AccessToken.CurrentAccessToken.TokenString;
    client.Login(message, (INSession session) =>
    {
      client.Connect(session);
      Debug.Log ("Successfully logged in.");
    }, (INError error) =>
    {
      Debug.Log ("Could not login. Attempting to register.");
      client.Register(message, (INSession session) =>
      {
        client.Connect(session);
        Debug.Log ("Successfully registered and logged in.");
      }, (INError error) =>
      {
        Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
      });
    });
  } else {
    Debug.LogErrorFormat ("Could not login to Facebook got '{0}'.", result.Error);
  }
});

----

==== Google

Similar to Facebook, authenticating via Google requires you to have an OAuth `AccessToken`. Once you have obtained the `AccessToken` you can use it to register and login to Nakama.

[source,csharp]
----
String oauthToken = "access-token-from-google";
var message = NAuthenticateMessage.Google(oauthToken);
client.Login(message, (INSession session) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.Log ("Could not login. Attempting to register.");
  client.Register(message, (INSession session) =>
  {
    client.Connect(session);
    Debug.Log ("Successfully registered and logged in.");
  }, (INError error) =>
  {
    Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
  });
});
----

==== Steam

NOTE: **Make sure you have a Steam application set up.**
A Steam App ID and Publisher Key are required; set these in the Nakama link:../../configure.adoc[configuration] file.

To authenticate with Steam, you first need a Steam `SessionToken` for the user. Once you have obtained the `SessionToken` you can use it to register and login to Nakama.

[source,csharp]
----
string sessionToken = "session-token-from-steam";
var message = NAuthenticateMessage.Steam(sessionToken);
client.Login(message, (INSession session) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.Log ("Could not login. Attempting to register.");
  client.Register(message, (INSession session) =>
  {
    client.Connect(session);
    Debug.Log ("Successfully registered and logged in.");
  }, (INError error) =>
  {
    Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
  });
});
----

==== Game Center

Nakama supports authentication using Game Center Player IDs on compatible Apple devices. This is a good frictionless authentication option as it requires no user input.

Users can be authenticated by sending the following Game Center credentials to the server: Player ID, Bundle ID, Timestamp, Salt, Signature, and Public Key URL. You'll need to dive into native Objective-C code as the `UnityEngine.SocialPlatforms.GameCenter` doesn't expose enough information to enable authentication.

TIP: **Required parameters**
Have a look at the relevant https://developer.apple.com/reference/gamekit/gklocalplayer/1515407-generateidentityverificationsign[iOS GameKit function reference^].

[source,csharp]
----
// These are passed in via your native Objective-C code...
string playerId;
string bundleId;
long timestamp;
string base64salt;
string base64signature;
string publicKeyUrl;

var message = NAuthenticateMessage.GameCenter(playerId, bundleId, timestamp, base64salt, base64signature, publicKeyUrl);
client.Login(message, (INSession session) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.Log ("Could not login. Attempting to register.");
  client.Register(message, (INSession session) =>
  {
    client.Connect(session);
    Debug.Log ("Successfully registered and logged in.");
  }, (INError error) =>
  {
    Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
  });
});
----

=== Custom

You can use a custom ID to authenticate users with Nakama. This is particularly useful if you have an external user identity service and would like to mirror the user IDs used in your system into Nakama.

Similar to Social Login, ensure that your custom ID has been registered with Nakama before attempting to login with it.

[source,csharp]
----
string customId = "your-custom-id";
var message = NAuthenticateMessage.Custom(customId);
client.Login(message, (INSession session) =>
{
  client.Connect(session);
  Debug.Log ("Successfully logged in.");
}, (INError error) =>
{
  Debug.Log ("Could not login. Attempting to register.");
  client.Register(message, (INSession session) =>
  {
    client.Connect(session);
    Debug.Log ("Successfully registered and logged in.");
  }, (INError error) =>
  {
    Debug.LogErrorFormat ("Could not login user: '{0}'.", error.Message);
  });
});
----

== Link / Unlink

Linking allows the user to login using more than one type of identifier. It is very similar to the registration process for each authentication type. You can only link credentials that are not already in use by another user.

The user needs to be logged in and have a connected session with the server.

[source,csharp]
----
string id = "id";
var message = SelfLinkMessage.Device(id);
client.Send(message, (bool completed) => {
  Debug.Log ("Successfully linked device ID to current user");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not link device ID: '{0}'.", error.Message);
});
----

To unlink, simply tell Nakama to remove the credentials:

[source,csharp]
----
string id = "id";
var message = SelfUnlinkMessage.Device(id);
client.Send(message, (bool completed) => {
  Debug.Log ("Successfully unlinked device ID from current user");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not unlink device ID: '{0}'.", error.Message);
});
----

== Fetch Self

The client can retrieve the currently logged-in user data from Nakama. This data includes common fields such as handle, fullname, avatar URL and timezone. Self will also include user's login information such as a list of device IDs associated and their social IDs.

[source,csharp]
----
var message = NSelfFetchMessage.Default();
client.Send(message, (INSelf self) => {
  Debug.LogFormat ("The user's ID is '{0}'.", self.Id);
  Debug.LogFormat ("The user's fullname is '{0}'.", self.Fullname); // may be null
  Debug.LogFormat ("The user's handle is '{0}'.", user.Handle);
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not retrieve self: '{0}'.", error.Message);
});
----

== Update Self

The client can update the information stored about the currently logged-in user, such as their handle, fullname, location, or lang.

[source,csharp]
----
var message = new NSelfUpdateMessage.Builder()
                    .AvatarUrl("http://graph.facebook.com/avatar_url")
                    .Fullname("My New Name")
                    .Lang("en")
                    .Location("San Francisco")
                    .Timezone("Pacific Time")
                    .Build();
client.Send(message, (bool completed) => {
  Debug.Log ("Successfully updated user information");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not update self: '{0}'.", error.Message);
});
----

== Fetch Users

Nakama can give the client common information about other users. The client needs to know the IDs of those users.

TIP: **Public user information**
Use this to display public user profiles, identify opponents in matches, and more.

[source,csharp]
----
var message = NUsersFetchMessage.Default(id);
client.Send(message, (INResultSet<INUser> results) => {
  Debug.LogFormat ("Fetched {0} users'.", results.Results.Count);
  foreach (INUser user in results.Results) {
    Debug.LogFormat ("The user's handle is '{0}'.", user.Handle);
  }
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not retrieve users: '{0}'.", error.Message);
});
----
