= User | Nakama server documentation

The core component of every client interaction with Nakama is the user. A user represents a unique identity in Nakama, and can have one or more unique identifiers attached - device IDs, email addresses, Facebook accounts, and more.


== Fetch Self

The client can retrieve the currently logged-in user data from Nakama. This data includes common fields such as handle, fullname, avatar URL and timezone. Self will also include user's login information such as a list of device IDs associated and their social IDs.

[source,csharp]
----
var message = NSelfFetchMessage.Default();
client.Send(message, (INSelf self) => {
  Debug.LogFormat ("The user's ID is '{0}'.", self.Id);
  Debug.LogFormat ("The user's fullname is '{0}'.", self.Fullname); // may be null
  Debug.LogFormat ("The user's handle is '{0}'.", user.Handle);
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not retrieve self: '{0}'.", error.Message);
});
----

== Update Self

The client can update the information stored about the currently logged-in user, such as their handle, fullname, location, or lang.

[source,csharp]
----
var message = new NSelfUpdateMessage.Builder()
                    .AvatarUrl("http://graph.facebook.com/avatar_url")
                    .Fullname("My New Name")
                    .Lang("en")
                    .Location("San Francisco")
                    .Timezone("Pacific Time")
                    .Build();
client.Send(message, (bool completed) => {
  Debug.Log ("Successfully updated user information");
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not update self: '{0}'.", error.Message);
});
----

== Fetch Users

Nakama can give the client common information about other users. The client needs to know the IDs of those users.

TIP: **Public user information**
Use this to display public user profiles, identify opponents in matches, and more.

[source,csharp]
----
var message = NUsersFetchMessage.Default(id);
client.Send(message, (INResultSet<INUser> results) => {
  Debug.LogFormat ("Fetched {0} users'.", results.Results.Count);
  foreach (INUser user in results.Results) {
    Debug.LogFormat ("The user's handle is '{0}'.", user.Handle);
  }
}, (INError error) =>
{
  Debug.LogErrorFormat ("Could not retrieve users: '{0}'.", error.Message);
});
----
