= Configure

== Configuration file settings

The `.yml` config file contains the full array of configuration parameters supported by Nakama.

The configuration file’s location depends on the startup system your distribution uses.

A configuration file path may also be specified on the command line with the `--config` option.

=== Basic configuration
* `name`: Unique node name. This name is also used in the log files. Default value is `"nakama-xxxx"`, where `xxxx` represents 4 random characters.
* `datadir`: Data directory to store server data. Absolute path to a writeable folder. Default value is ``"./data/"``.
* `port`: The port to listen on when accepting connections from the client. This is listening on all interfaces. Default value is `7350`. Unless explicitly defined, other ports will be chosen sequentially from here upwards.
* `ops_port`: The port to listen on when accepting connections for the ops dashboard. This is listening on all interfaces. Default value is `7351`.
* `dsns`: Fully qualified list of JDBC addresses to CockroachDB servers. Default value is `root@127.0.0.1:26257`.

=== Session configs
* `encryption_key`: Encryption key used to produce the client token. Default value is ``"defaultencryptionkey"``.

WARNING: *Set your encryption key*
It is highly recommended to change the default value for production servers.

* `token_expiry_ms`: Validity period of client token in milliseconds. Default value is `60000`.

=== Transport settings
* `server_key`: Server key to use to establish a connection to the server. Default value is ``"defaultkey"``.

WARNING: *Set your server key*
It is highly recommended to change the default value for production servers.

* `max_message_size_bytes`: Maximum amount of data in bytes allowed to be read from the client socket per message. Default value is `1024`.
* `write_wait_ms`: Amount of time in milliseconds to wait for an ack from the client when writing data. Default value is `5000`.
* `pong_wait_ms`: Amount of time in milliseconds to wait for a pong message from the client after sending a ping. Default value is `10000`.
* `ping_period_ms`: Amount of time in milliseconds to wait between client ping messages. This value must be less than the `pong_wait_ms`. Default value is `8000`.

=== Database connection settings
* `conn_max_lifetime_ms`: Time in milliseconds to reuse a database connection before the connection is killed and a new one is created. Default value is `60000`.
* `max_open_conns`: Maximum number of allowed open connections to the database. Default value is `0` (which mean no limit).
* `max_idle_conns`: Maximum number of allowed open but unused connections to the database. Default value is `0` (which means no limit).

=== Social providers

==== Steam
* `publisher_key`: Steam Publisher Key value. Default value is `""`.
* `app_id`: Steam App ID. Default value is `0`.

NOTE: *Steam login*
With the default values, Steam login is disabled.

The following options are available in https://heroiclabs.com/managedcloud.html#enterprise[Nakama Enterprise]:

=== Basic configuration
* `join`: List of node addresses to connect to form a cluster. Default value is `""`.

=== Cluster configuration

* `rpc_port`: Port to bind to for inter-cluster communication. Default value is `7353`.
* `gossip_bindaddr`: Address to bind for the discovery service. Default value is ``"127.0.0.1"``. Gossip traffic will not be received on interfaces other than the specified one.
* `gossip_bindport`: Port to bind for the discovery service. Default value is `7352`.

=== Sample Configuration:

[source,yml]
----
  name: nakama-node-1
  datadir: "./data/"
  port: 7350
  ops_port: 7351
  dsns:
    - "root@127.0.0.1:26257"
  join:
    - "10.0.0.2:7352"
    - "10.0.0.3:7352"

  cluster:
    rpc_port: 7353
    gossip_bindaddr: "127.0.0.1"
    gossip_bindport: 7352

  session:
    encryption_key: "defaultencryptionkey"
    token_expiry_ms: 60000

  transport:
    server_key: "defaultkey"
    max_message_size_bytes: 1024 # bytes
    write_wait_ms: 5000
    pong_wait_ms: 10000
    ping_period_ms: 8000 # Must be less than pong_wait_ms

  database:
    conn_max_lifetime_ms: 60000
    max_open_conns: 0
    max_idle_conns: 0

  social:
    steam:
      publisher_key: ""
      app_id: 0
----

== Command line options

These options can be passed to the Nakama server on the command line on startup. These options can also be set in the configuration file, however any command-line arguments take precedence.

* `--config`: Absolute path to a configuration file.
* `--db`: Fully qualified JDBC address to a CockroachDB server. This is in the form of `jdbc://user:password@hostname:port`.
* `--data-dir`: Data directory to store server data. Absolute file to a writeable folder.
* `--name`: Unique node name. This name is also used in the log files.
* `--port`: The port to listen on when accepting connections from the client. This is listening on all interfaces by default. Unless explicitly defined, other ports will be chosen sequentially from here upwards.
* `--ops-port`: The port to listen on when accepting connections for the ops dashboard. This is listening on all interfaces by default.

The following options are available in https://heroiclabs.com/managedcloud.html#enterprise[Nakama Enterprise]:

* `--join`: Address of a node to connect to, either to join an existing cluster or form a new one.
